services:
  backend:
    image: andomo3/safetransit-backend:dev
    platform: linux/amd64
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  frontend:
    image: andomo3/safetransit-frontend:dev
    platform: linux/amd64
    ports:
      - "5173:5173"
    depends_on:
      - backend
